;;; +config.elfeed.el -*- lexical-binding: t; -*-

(after! elfeed
  (setq elfeed-search-face-alist
        '((unread    elfeed-search-unread-title-face)
          (censored  head-outline-1)
          (censored  head-outline-2)
          (censored  head-outline-3)
          (censored  head-outline-4)
          (censored  head-outline-8)
          (censored  head-outline-6)
          (censored  head-outline-7)
          (censored  head-outline-8)
          (censored  head-outline-5)
          (star      elfeed-star-face)))

  (map! :map elfeed-search-mode-map
        :n "s-)" '(lambda () (interactive) (elfeed-search-set-filter "+unread "))
        :n "s-!" '(lambda () (interactive) (elfeed-search-set-filter "+unread +censored "))
        :n "s-@" '(lambda () (interactive) (elfeed-search-set-filter "+unread +censored "))
        :n "s-#" '(lambda () (interactive) (elfeed-search-set-filter "+unread +censored "))
        :n "s-$" '(lambda () (interactive) (elfeed-search-set-filter "+unread +censored "))
        :n "s-%" '(lambda () (interactive) (elfeed-search-set-filter "+unread +censored "))
        :n "s-^" '(lambda () (interactive) (elfeed-search-set-filter "+unread +censored "))
        :n "s-&" '(lambda () (interactive) (elfeed-search-set-filter "+unread +censored "))
        :n "s-*" '(lambda () (interactive) (elfeed-search-set-filter "+unread +censored "))
        :n "s-(" '(lambda () (interactive) (elfeed-search-set-filter "+unread +censored "))
        :n "s-0" '(lambda () (interactive) (elfeed-search-set-filter ""))
        :n "s-1" '(lambda () (interactive) (elfeed-search-set-filter "+censored "))
        :n "s-2" '(lambda () (interactive) (elfeed-search-set-filter "+censored "))
        :n "s-3" '(lambda () (interactive) (elfeed-search-set-filter "+censored "))
        :n "s-4" '(lambda () (interactive) (elfeed-search-set-filter "+censored "))
        :n "s-5" '(lambda () (interactive) (elfeed-search-set-filter "+censored "))
        :n "s-6" '(lambda () (interactive) (elfeed-search-set-filter "+censored "))
        :n "s-7" '(lambda () (interactive) (elfeed-search-set-filter "+censored "))
        :n "s-8" '(lambda () (interactive) (elfeed-search-set-filter "+censored "))
        :n "s-9" '(lambda () (interactive) (elfeed-search-set-filter "+censored "))
        :n "s-`" '(lambda () (interactive) (elfeed-search-set-filter "+star "))
        ))
